FROM python:3.10

WORKDIR /opt
COPY requirement.txt /opt/
RUN python -m pip install -r requirement.txt
RUN python -m pip install google-generativeai

COPY src /opt/src
COPY config.yml worker_tools.py /opt/

CMD python -u worker_tools.py